language: generic

services:
  - docker

before_install:
  - docker build -t robinerickson/incubo-docker ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true robinerickson/incubo-docker npm test

after_success:
  - docker build -t robinerickson/incubo-client ./client
  - docker build -t robinerickson/incubo-nginx ./nginx
  - docker build -t robinerickson/incubo-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push robinerickson/incubo-client
  - docker push robinerickson/incubo-nginx
  - docker push robinerickson/incubo-server